G|*|G.Administrators|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|Down_Files|G.Anonymous|1
G|Man_PgCat|G.MVSD|1
G|Man_Disc|G.MVSD|1
G|Man_Files|G.MVSD|1
G|Man_Snips_Temps|G.MVSD|1
G|Man_NavPath|G.MVSD|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|Down_Files|G.Users|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|Down_Files|U.kpn_pm|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|List|U.kpn_pm|0
P.Index|Rd_1Pg|G.Anonymous|1
P.Index|Rd_1Disc|G.Anonymous|1
P.Index|Down_1Attn|G.Anonymous|1
P.Index|*|G.Anonymous|0
P.Brainnet_Index|*|G.Anonymous|0
P.KnowledgeBase.KB_Index|Rd_1Pg|G.Anonymous|1
P.KnowledgeBase.KB_Index|Rd_1Disc|G.Anonymous|1
P.KnowledgeBase.KB_Index|Pst_1Disc|G.Anonymous|1
P.KnowledgeBase.KB_Index|Down_1Attn|G.Anonymous|1
P.KnowledgeBase.KB_Index|*|G.Anonymous|0
P.KPN-NEC.KPN-NEC_Index|*|G.Anonymous|0
N.MVSD|*|G.Anonymous|0
G|*|U.devid|1
P.Insights.Insights_Index|Rd_1Pg|G.Anonymous|1
P.Insights.Insights_Index|Rd_1Disc|G.Anonymous|1
P.Insights.Insights_Index|Pst_1Disc|G.Anonymous|1
P.Insights.Insights_Index|Down_1Attn|G.Anonymous|1
P.Insights.Insights_Index|*|G.Anonymous|0
N.|Rd_Pg|G.Anonymous|1
N.|Rd_Disc|G.Anonymous|1
N.|Down_Attn|G.Anonymous|1
N.|*|G.Anonymous|0
N.KnowledgeBase|*|G.Anonymous|0
N.Insights|Rd_Pg|G.Anonymous|1
N.Insights|Rd_Disc|G.Anonymous|1
N.Insights|Pst_Disc|G.Anonymous|1
N.Insights|Down_Attn|G.Anonymous|1
N.Insights|*|G.Anonymous|0
N.Brainnet|*|G.Anonymous|0
N.KPN-NEC|Rd_Pg|G.KPN_NEC|1
N.KPN-NEC|Rd_Disc|G.KPN_NEC|1
N.KPN-NEC|Pst_Disc|G.KPN_NEC|1
N.KPN-NEC|Down_Attn|G.KPN_NEC|1
N.KPN-NEC|*|G.KPN_NEC|0
N.KPN-NEC|Rd_Pg|G.MVSD|1
N.KPN-NEC|Down_Attn|G.MVSD|1
N.KPN-NEC|*|G.MVSD|0
N.KPN-NEC|*|G.Anonymous|0
G|*|U.procm|1
N.ICTAutomatisering|*|G.Anonymous|0
N.NexusVerus|*|G.Anonymous|0
