G|*|G.Administrators|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|Down_Files|G.Anonymous|1
G|Man_PgCat|G.MVSD|1
G|Man_Disc|G.MVSD|1
G|Man_Files|G.MVSD|1
G|Man_Snips_Temps|G.MVSD|1
G|Man_NavPath|G.MVSD|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|Down_Files|G.Users|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|Down_Files|U.kpn_pm|1
D.(ScrewTurn.Wiki.FilesStorageProvider)/|List|U.kpn_pm|0
P.Index|Rd_1Pg|G.Anonymous|1
P.Index|Rd_1Disc|G.Anonymous|1
P.Index|Down_1Attn|G.Anonymous|1
P.Index|*|G.Anonymous|0
P.Brainnet_Index|*|G.Anonymous|0
P.KPN-NEC.KPN-NEC_Index|*|G.Anonymous|0
N.MVSD|*|G.Anonymous|0
G|*|U.devid|1
N.|Rd_Pg|G.Anonymous|1
N.|Rd_Disc|G.Anonymous|1
N.|Down_Attn|G.Anonymous|1
N.|*|G.Anonymous|0
N.KnowledgeBase|*|G.Anonymous|0
N.Brainnet|*|G.Anonymous|0
N.KPN-NEC|Rd_Pg|G.KPN_NEC|1
N.KPN-NEC|Rd_Disc|G.KPN_NEC|1
N.KPN-NEC|Pst_Disc|G.KPN_NEC|1
N.KPN-NEC|Down_Attn|G.KPN_NEC|1
N.KPN-NEC|*|G.KPN_NEC|0
N.KPN-NEC|Rd_Pg|G.MVSD|1
N.KPN-NEC|Down_Attn|G.MVSD|1
N.KPN-NEC|*|G.MVSD|0
N.KPN-NEC|*|G.Anonymous|0
G|*|U.procm|1
N.NexusVerus|*|G.Anonymous|0
N.ICTAutomatisering|*|G.Anonymous|0
P.MainPage|Rd_1Pg|G.ICTA|1
P.MainPage|*|G.ICTA|0
N.Insights|*|G.Anonymous|0
N.Hoogendoorn|*|G.Anonymous|0
N.Hoogendoorn|Rd_Pg|G.HGMx|1
N.Hoogendoorn|Rd_Disc|G.HGMx|1
N.Hoogendoorn|Pst_Disc|G.HGMx|1
N.Hoogendoorn|Down_Attn|G.HGMx|1
N.Hoogendoorn|*|G.HGMx|0
N.Ciber|*|G.Anonymous|0
N.Ciber|Rd_Pg|G.Ciber|1
N.Ciber|Rd_Disc|G.Ciber|1
N.Ciber|Pst_Disc|G.Ciber|1
N.Ciber|Down_Attn|G.Ciber|1
N.Ciber|*|G.Ciber|0
N.NexusVerus|Rd_Pg|G.ICTA|1
N.NexusVerus|Rd_Disc|G.ICTA|1
N.NexusVerus|Down_Attn|G.ICTA|1
N.NexusVerus|*|G.ICTA|0
N.MVSD|Rd_Pg|G.ICTA|1
N.MVSD|Rd_Disc|G.ICTA|1
N.MVSD|Down_Attn|G.ICTA|1
N.MVSD|*|G.ICTA|0
N.KPN-NEC|Rd_Pg|G.ICTA|1
N.KPN-NEC|Rd_Disc|G.ICTA|1
N.KPN-NEC|Down_Attn|G.ICTA|1
N.KPN-NEC|*|G.ICTA|0
N.KnowledgeBase|Rd_Pg|G.ICTA|1
N.KnowledgeBase|Rd_Disc|G.ICTA|1
N.KnowledgeBase|Down_Attn|G.ICTA|1
N.KnowledgeBase|*|G.ICTA|0
N.ICTAutomatisering|Rd_Pg|G.ICTA|1
N.ICTAutomatisering|Rd_Disc|G.ICTA|1
N.ICTAutomatisering|Down_Attn|G.ICTA|1
N.ICTAutomatisering|*|G.ICTA|0
N.Hoogendoorn|Rd_Pg|G.ICTA|1
N.Hoogendoorn|Rd_Disc|G.ICTA|1
N.Hoogendoorn|Down_Attn|G.ICTA|1
N.Hoogendoorn|*|G.ICTA|0
N.Ciber|Rd_Pg|G.ICTA|1
N.Ciber|Rd_Disc|G.ICTA|1
N.Ciber|Down_Attn|G.ICTA|1
N.Ciber|*|G.ICTA|0
N.Brainnet|Rd_Pg|G.ICTA|1
N.Brainnet|Rd_Disc|G.ICTA|1
N.Brainnet|Down_Attn|G.ICTA|1
N.Brainnet|*|G.ICTA|0
