WikiTitle = ScrewTurn Wiki
MainUrl = https://wiki.insightsgtd.nl/
ContactEmail = me@insightsgtd.nl
SenderEmail = celio.moreira@insightsgtd.nl
ErrorsEmails = 
SmtpServer = google.com
SmtpPort = 25
SmtpUsername = 
SmtpPassword = 
SmtpSsl = no
Theme = Default
DefaultPage = Index
DateTimeFormat = ddd', 'dd' 'MMM' 'yyyy' 'HH':'mm
DefaultLanguage = en-US
DefaultTimezone = 60
EnableDoubleClickEditing = no
EnableSectionEditing = yes
EnablePageToolbar = yes
EnableViewPageCode = yes
EnablePageInfoDiv = yes
DisableBreadcrumbsTrail = no
ProcessSingleLineBreaks = no
UseVisualEditorAsDefault = no
KeptBackupNumber = -1
UsersCanRegister = yes
AccountActivationMode = EMAIL
UsersGroup = Users
AdministratorsGroup = Administrators
AnonymousGroup = Anonymous
DisableCaptchaControl = no
DisableConcurrentEditing = yes
ChangeModerationMode = RequirePageEditingPermissions
AllowedFileTypes = jpg|jpeg|gif|png|tif|tiff|bmp|htm|html|zip|rar|pdf|txt|doc|xls|ppt|docx|xlsx|pptx|vsd|vpp
MaxFileSize = 10240
ScriptTagsAllowed = no
LoggingLevel = 3
MaxLogSize = 64
DisableAutomaticVersionCheck = no
DisableCache = no
CacheSize = 100
CacheCutSize = 20
EnableViewStateCompression = yes
EnableHttpCompression = yes
Theme-KPN-NEC = Default
Theme-MVSD = Default
Theme-KnowledgeBase = Default
MaxRecentChangesToDisplay = 10
RssFeedsMode = Summary
EnableSectionAnchors = yes
AutoGeneratePageNames = yes
DisplayGravatars = yes
UsernameRegex = ^\w[\w\ !$@%^\.\(\)]{3,25}$
PasswordRegex = ^\w[\w~!@#$%^\(\)\[\]\{\}\.,=\-_\ ]{6,25}$
FileDownloadCountFilterMode = CountAll
FileDownloadCountFilter = 
IpHostFilter = 
Theme-Insights = Default
LastPageIndexing = 20150507171452
Theme-Brainnet = Default
DefaultPagesProvider = ScrewTurn.Wiki.PagesStorageProvider
DefaultUsersProvider = ScrewTurn.Wiki.UsersStorageProvider
DefaultFilesProvider = ScrewTurn.Wiki.FilesStorageProvider
DefaultCacheProvider = ScrewTurn.Wiki.CacheProvider
ListSize = 50
Theme-NexusVerus = Default
Theme-ICT Automatisering = Default
Theme-ICTAutomatisering = Default-v2
Theme-Hoogendoorn = Default
