G|2015/01/28 13:54:25|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/01/28 13:54:25|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/01/28 13:54:25|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|MessageFormatter - Init success|MessageFormatter
G|2015/01/28 13:54:25|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/01/28 13:54:25|ScrewTurn Wiki is ready|SYSTEM
G|2015/01/28 13:54:35|Starting automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2015/01/28 13:54:39|Finished automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2015/01/28 13:54:39|User procm logged in|SYSTEM
G|2015/02/02 10:37:14|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:15|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/02 10:37:15|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:15|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:15|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/02 10:37:15|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/02 10:37:15|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:15|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|MessageFormatter - Init success|MessageFormatter
G|2015/02/02 10:37:16|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/02/02 10:37:16|ScrewTurn Wiki is ready|SYSTEM
G|2015/02/02 10:37:26|User procm logged in|SYSTEM
G|2015/02/03 13:05:21|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/02/03 13:05:21|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/02/03 13:05:22|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/03 13:05:22|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/02/03 13:05:22|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/02/03 13:05:22|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/03 13:05:22|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/03 13:05:22|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/02/03 13:05:22|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/02/03 13:05:22|MessageFormatter - Init success|MessageFormatter
G|2015/02/03 13:05:22|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/02/03 13:08:21|User procm logged in|SYSTEM
G|2015/02/05 16:44:57|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/05 16:44:57|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|MessageFormatter - Init success|MessageFormatter
G|2015/02/05 16:44:57|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/02/05 16:44:57|ScrewTurn Wiki is ready|SYSTEM
G|2015/02/05 16:45:07|Starting automatic rebuilding index for provider: Local Pages Provider|SYSTEM
E|2015/02/05 16:45:08|Message indexing error for Brainnet.Brainnet_Index:0 (skipping message): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexMessage(PageInfo page, Int32 id, String subject, DateTime dateTime, String body)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for Brainnet.Current-Issues (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for Brainnet.ICT-Administration (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for Brainnet.ICT_Infrastructuur (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for Brainnet.Optimization-OPerations-Services (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for Brainnet.Research (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for Brainnet.Software-installation-configuration (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for ICTAutomatisering.ICTAutomatisering_Hardware (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for ICTAutomatisering.ICTAutomatisering_Ideas (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for ICTAutomatisering.ICTAutomatisering_MonitoringTool (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:08|Page indexing error for ICTAutomatisering.ICTAutomatisering_RhoMobile (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for Insights.Accomplishments (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for Insights.Insights_Index (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.Database (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.Deployment-van-een-nieuwe-website-incl-SQL-database-op-test3-mvsd-nl (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.EasyWebEditNet website opzetten vanuit de Codebase (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.Email_Clients-Servers (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.Exchange_Virtualization (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.IIS-6-Deploying-an-url-forward (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.IIS-6-Deploying-and-configuring-a-new-website (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:09|Page indexing error for KnowledgeBase.IIS-6-Deploying-and-configuring-a-new-website-into-a-virtual-directory (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:10|Page indexing error for KnowledgeBase.KB_Development_Guidelines (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:11|Page indexing error for MVSD.MVSD_EasyWebEdit (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:12|Page indexing error for MVSD.MVSD_Index (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:12|Page indexing error for MVSD.MVSD_Infra (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2015/02/05 16:45:12|Page indexing error for MVSD.MVSD_PhoneNumbers (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
G|2015/02/05 16:45:12|User procm logged in|SYSTEM
G|2015/02/09 11:49:17|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:17|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:17|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/09 11:49:18|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|MessageFormatter - Init success|MessageFormatter
G|2015/02/09 11:49:18|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/02/09 11:49:18|ScrewTurn Wiki is ready|SYSTEM
G|2015/02/09 11:49:43|User procm logged in|SYSTEM
G|2015/02/09 11:51:46|Page update requested for Insights.Insights_Index|procm
G|2015/02/09 11:51:46|Page Content updated for Insights.Insights_Index|SYSTEM
G|2015/02/09 11:51:47|Page Insights.Insights_Index rebound|SYSTEM
G|2015/02/09 11:52:57|Page update requested for Insights.Insights_Index|procm
G|2015/02/09 11:52:59|Page Content updated for Insights.Insights_Index|SYSTEM
G|2015/02/09 11:52:59|Page Insights.Insights_Index rebound|SYSTEM
G|2015/02/09 11:53:26|Page update requested for Insights.Insights_Index|procm
G|2015/02/09 11:53:27|Page Content updated for Insights.Insights_Index|SYSTEM
G|2015/02/09 11:53:28|Page Insights.Insights_Index rebound|SYSTEM
G|2015/02/09 11:53:57|Page update requested for Insights.Insights_Index|procm
G|2015/02/09 11:53:59|Page Content updated for Insights.Insights_Index|SYSTEM
G|2015/02/09 11:53:59|Page Insights.Insights_Index rebound|SYSTEM
G|2015/02/09 11:56:50|Page update requested for Insights.Insights_Index|procm
E|2015/02/09 11:56:52|Page indexing error for Insights.Insights_Index (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\MyProjects\Programming\workbench.cmo\ScrewTurn-wiki-3.0.5.600.FileSystem\WebApplication\App_Data\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
G|2015/02/09 11:56:52|Page Content updated for Insights.Insights_Index|SYSTEM
G|2015/02/09 11:56:52|Page Insights.Insights_Index rebound|SYSTEM
G|2015/02/09 12:08:11|Page update requested for Insights.Accomplishments|procm
G|2015/02/09 12:08:11|Page Content updated for Insights.Accomplishments|SYSTEM
G|2015/02/09 12:08:11|Page Insights.Accomplishments rebound|SYSTEM
G|2015/02/09 12:08:24|Page update requested for Insights.Accomplishments|procm
G|2015/02/09 12:08:26|Page Content updated for Insights.Accomplishments|SYSTEM
G|2015/02/09 12:08:26|Page Insights.Accomplishments rebound|SYSTEM
G|2015/02/23 18:18:32|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:32|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:33|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/23 18:18:33|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:33|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:33|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/23 18:18:33|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/23 18:18:33|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:33|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|MessageFormatter - Init success|MessageFormatter
G|2015/02/23 18:18:34|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/02/23 18:18:34|ScrewTurn Wiki is ready|SYSTEM
G|2015/02/23 18:18:44|Starting automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2015/02/23 18:18:48|Finished automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2015/02/27 20:57:16|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/27 20:57:16|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|MessageFormatter - Init success|MessageFormatter
G|2015/02/27 20:57:16|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/02/27 20:57:16|ScrewTurn Wiki is ready|SYSTEM
G|2015/02/27 20:57:31|User procm logged in|SYSTEM
G|2015/03/01 21:50:01|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:01|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:01|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/01 21:50:01|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:01|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:01|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/01 21:50:01|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/01 21:50:02|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|MessageFormatter - Init success|MessageFormatter
G|2015/03/01 21:50:02|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/03/01 21:50:02|ScrewTurn Wiki is ready|SYSTEM
G|2015/03/01 21:50:13|User procm logged in|SYSTEM
G|2015/03/09 13:46:19|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:19|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/09 13:46:20|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|MessageFormatter - Init success|MessageFormatter
G|2015/03/09 13:46:20|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/03/09 13:46:20|ScrewTurn Wiki is ready|SYSTEM
G|2015/03/09 13:46:30|Starting automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2015/03/09 13:46:33|Finished automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2015/03/09 14:11:32|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:32|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:32|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/09 14:11:32|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:32|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:32|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/09 14:11:32|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2015/03/09 14:11:32|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:32|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|MessageFormatter - Init success|MessageFormatter
G|2015/03/09 14:11:33|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2015/03/09 14:11:33|ScrewTurn Wiki is ready|SYSTEM
