E|2014/03/03 11:54:42|Page indexing error for MVSD.Holland-Labour-Group-(HLG) (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.Housingmatters (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.HUTAC (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexMappings.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.Keith-Johnstone (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.Kraameiland (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.MVSD-Website (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexDocuments.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.MVSD-Website-Demo (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.MVSD-Website-Economy (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
E|2014/03/03 11:54:42|Page indexing error for MVSD.MVSD_EasyShop (skipping page): System.IO.IOException: The process cannot access the file 'D:\Transfer.cmo\Dropbox\Wiki\MyData\IndexWords.cs' because it is being used by another process.{BR}   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath){BR}   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy){BR}   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share){BR}   at ScrewTurn.Wiki.IndexStorer.SaveData(DumpedChange data, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.IndexStorerBase.IndexChangedHandler(Object sender, IndexChangedEventArgs e){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.OnIndexChange(IDocument document, IndexChangeType change, DumpedChange changeData, Object state){BR}   at ScrewTurn.Wiki.SearchEngine.InMemoryIndexBase.StoreDocument(IDocument document, String[] keywords, String content, Object state){BR}   at ScrewTurn.Wiki.PagesStorageProvider.IndexPage(PageContent content)|Local Pages Provider+SYSTEM
G|2014/03/03 11:54:43|Finished automatic rebuilding index for provider: Local Pages Provider|SYSTEM
G|2014/03/03 11:58:05|Page update requested for ICTAutomatisering.ICTAutomatisering_RhoMobile|procm
G|2014/03/03 11:58:06|Page Content updated for ICTAutomatisering.ICTAutomatisering_RhoMobile|SYSTEM
G|2014/03/03 11:58:06|Page ICTAutomatisering.ICTAutomatisering_RhoMobile rebound|SYSTEM
G|2014/03/03 11:58:19|Page update requested for ICTAutomatisering.ICTAutomatisering_RhoMobile|procm
G|2014/03/03 11:58:20|Page Content updated for ICTAutomatisering.ICTAutomatisering_RhoMobile|SYSTEM
G|2014/03/03 11:58:20|Page ICTAutomatisering.ICTAutomatisering_RhoMobile rebound|SYSTEM
G|2014/03/03 14:00:21|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:21|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:21|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2014/03/03 14:00:21|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:21|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2014/03/03 14:00:22|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2014/03/03 14:00:22|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|MessageFormatter - Init success|MessageFormatter
G|2014/03/03 14:00:22|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2014/03/03 14:00:22|ScrewTurn Wiki is ready|SYSTEM
G|2014/03/03 14:16:01|User procm logged in|SYSTEM
G|2014/03/06 15:31:20|Provider Local Files Provider loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Local Users Provider loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider SQL Server Users Storage Provider loaded (Disabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Local Pages Provider loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Local Cache Provider loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider SQL Server Files Storage Provider loaded (Disabled)|SYSTEM
G|2014/03/06 15:31:20|Provider SQL Server Pages Storage Provider loaded (Disabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Download Counter Plugin loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Footnotes Plugin loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|MessageFormatter - Init success|MessageFormatter
G|2014/03/06 15:31:20|Provider MessageFormatter loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Multilanguage Content Plugin loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Syntax Highlighter v2.0 support loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider Rating Manager Plugin loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider NumericHeaderFormatter loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|Provider TableFormatter loaded (Enabled)|SYSTEM
G|2014/03/06 15:31:20|ScrewTurn Wiki is ready|SYSTEM
G|2014/03/06 15:31:52|User procm logged in|SYSTEM
G|2014/03/06 15:34:40|Page update requested for Insights.Accomplishments|procm
G|2014/03/06 15:34:40|Page Content updated for Insights.Accomplishments|SYSTEM
G|2014/03/06 15:34:40|Page Insights.Accomplishments rebound|SYSTEM
G|2014/03/06 15:36:03|Page update requested for Insights.Accomplishments|procm
G|2014/03/06 15:36:04|Page Content updated for Insights.Accomplishments|SYSTEM
G|2014/03/06 15:36:04|Page Insights.Accomplishments rebound|SYSTEM
G|2014/03/06 15:37:13|Page update requested for Insights.Accomplishments|procm
G|2014/03/06 15:37:13|Page Content updated for Insights.Accomplishments|SYSTEM
G|2014/03/06 15:37:13|Page Insights.Accomplishments rebound|SYSTEM
G|2014/03/06 15:39:39|Page update requested for Insights.Accomplishments|procm
G|2014/03/06 15:39:39|Page Content updated for Insights.Accomplishments|SYSTEM
G|2014/03/06 15:39:39|Page Insights.Accomplishments rebound|SYSTEM
