Workspace Management
procm|2014/02/17 14:54:17
##PAGE##
{TOC}

==== [http://www.ressoftware.com/products/res-workspace-manager|RES WorkpaceManager]====
<PRE>
'''Action List:'''

* Application Management
** Create Start Menu folders and Managed Applications.
* Drive and Port Mappings
** Create managed drive mappings.
* Printers
** Create managed network printers.
* Folder Redirection
** Create managed folder redirections.
* Desktop Configuration
** Review the currently configured background.
** Review and adapt Lockdown and Behavior settings.
** Review the currently configured screensaver.
* Global User Settings
** Add global User Settings. Depending on your RES Workspace Manager edition, add application-level User Settings.
* RES Automation Manager
** Configure RES Automation Manager integration.
* Additional example objects
** Review the examples at Composition > Actions By Type > User Registry and create your own based on these examples.
** Review the example Network Printers at Composition > Actions By Type > Printers and create your own based on these examples.
</PRE>

((( '''Additional resources:'''
* Help File (use F1 in the console)
* Knowledge Base: [http://www.ressoftware.com/knowledgebase]
* Administration Guide: [http://support.ressoftware.com/workspacemanageradminguide2012]
* Best Practices White Papers: [http://www.ressoftware.com/support/best-practices-white-papers]
* Learning Management System: [http://tutorials.ressoftware.com]

Action List generated by Célio Renato Costa Moreira on 7-11-2012 14:38:40 )))

